name: Deploy ACCESS-OM2
on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    name: Deploy
    uses: access-nri/build-cd/.github/workflows/deploy-1-setup.yml@main
    permissions:
      contents: write
