name: PR Closed Cleanup
# Remove prereleases that were part of a closed PR, so we save space
# on our deployment targets. If needed, one can still get the
# spack.yaml as part of the closed PR and revive it themselves.
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - backport/*.*
    paths:
      - config/**
      - spack.yaml
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      version-pattern: ${{ steps.version.outputs.pattern }}
    steps:
      - name: Version Pattern
        id: version
        # For example, `access-om2-pr12-*`
        run: |
          repo_name_lower=$(echo ${{ github.event.repository.name }} | tr [:upper:] [:lower:])
          echo "pattern=${repo_name_lower}-pr${{ github.event.pull_request.number }}-*" >> $GITHUB_OUTPUT

  undeploy-prereleases:
    name: Undeploy Prereleases
    needs:
      - setup
    uses: access-nri/build-cd/.github/workflows/undeploy-1-setup.yml@main
    with:
      version-pattern: ${{ needs.setup.outputs.version-pattern }}
    secrets: inherit
